#? Configurações básicas da aplicação
spring.application.name=core
server.port=80

#? Configurações do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.datasource.url=jdbc:h2:mem:tarefasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#?? Config que, quando há alteração nas entidades, realiza um update nas tabelas sem apagar dados existentes.
spring.jpa.hibernate.ddl-auto=update
